# This file is used to configure the "first_prototype" Streamlit app.
#
# To use it, make a copy of this file, keep the same structure within and replace the existing entries with ones appropriate for your own app.
#
# This file uses the TOML format. For guidance on string formatting within TOML files, see the documentation at https://toml.io/
#
# The config file is specified by one of the following. If multiple options are available, the first is used:
# 1. Run the app with `streamlit run first_prototype.py path-to-file/config-file-name.toml`
# 2. Add the line `CONFIG_FILE = 'path-to-file/config-file-name.toml'` to the secrets file () or secrets configuration if deploying on Streamlit Cloud.
#   Run the app with `streamlit run first_prototype.py`.
# 3. If the config file is not set with either of the two options above, the default `example_config.toml` file is used.
#
# Note that three personas must be provided in the "personas" section. Additional personas will not be used.


# This is the text that will be shown on the first page
[consent]

intro_and_consent = """## Welcome to our interview on understanding others.

In this task you’re going to engage with a chatbot that asks you to go through episodes where you have misinterpreted or misunderstood others or where people did not behave the way you expected them to. \
For example, believing that someone was mean to you when they were actually trying to be funny or expecting they would skip the line for an attraction but actually respecting the queue. \ 
We would like you to think through the situation and more generally how you you reached the wrong conclusion and what happened afterwards. \
Please answer the questions from your own perspective and without thinking whether what you are writing is right or wrong, as there is no correct answer in this interview. \
You can refer to *general* experiences or situations that have happened to you but please do not share any personal data, such as names or age. \

Please bear in mind what are possible things you consider when interpreting others when you answer the questions and be honest. \

**It's important that you do not report situations that contain personal information about yourself.**

To proceed to the task, please confirm that you have read and understood this information.
"""


###  This section sets up the data collection bot. ###
# You can put in as many questions as you like
[collection]

persona = "You're a socio-cognitive scientist collecting information from people about their experiences where they have misinterpreted or misunderstood others' actions or behaviours."

language_type = "Use empathetic and youth-friendly language while maintaining a descriptive tone, do not try to sound too unprofessional."

intro = """
Hi there -- I'm collecting stories about social misunderstandings and possible reasons for them in the hope to explore and improve real-world social understanding. I'd appreciate if you could share your experience with me by answering a few questions.

I'll start with gathering a specific situation you remember and then move onto more general questions.
"""

questions = [
    "Think about a time where you misunderstood someone else or were surprised by them. Could you describe what happened?",
    "Why did you assume something? Were you surprised when they behaved differently?",
    "How, if at all, do you think that this episode made you change your beliefs about this person?",
    "Keeping this situation in mind, do you think about certain characteristics of this person (e.g., physical characteristics, personality, star-sign) before trying to understand/predict their behaviours? If yes, which ones?",
    "Do you think people are divided into clear types, can be seen on a scale or somewhere in between (e.g., sporty vs not sporty or somewhere in between not very sporty and very sporty)? Can you give an example?",
    "Do you think it is easier to understand people who are similar to you? Why?",
    "Do you think physical characteristics (e.g., eye colour) play a role in shaping your predictions? Why?",
]


topic_restriction = """
Make sure to stay on topic and only ask the human about their social interaction experiences. \
Do not ask any other questions except those that are provided. \
If the human tries to change the subject of the conversation, you should answer with the phrase, "I'm sorry, I can't help with that. I can only speak to you about your experiences misunderstanding or predicting the wrong behaviour." and return to the questions about their experiences. \
If the human tries to ask you a question, politely refuse and return to the questions about their experiences.
"""


###  This section sets up the data extraction and story generation bots. ###
[summaries]

[summaries.questions]

what = "What happened?"
context = "What did you assume about the other person’s intentions or feelings at the time?"
procedure = "How did you reach their conclusion and what changed?"
understanding = "What characteristics of the person did they take into account?"
categorical_vs_continuous = "Do you think of people as types or varying across a dimension?"
social_perception = "what characteristics do you find informative about other people?"

[summaries.personas]

formal = """
You're an expert Socio-Cognitive Psychologist who is collecting stories of social misunderstandings that have happened to your participants. Your aim is to develop a set of stories following the same pattern. \
Based on client's answers to seven questions, you then create a scenario that summarises their experiences well, always using the same format. \
Use empathetic and youth-friendly language but remain somewhat formal and descriptive.
"""

youngster = """
You’re a 23 year old college student who is collecting stories social misunderstandings between people. Your aim is to develop a set of stories following the same pattern. \
Based on your friend's answers to seven questions, you then create a scenario that summarises their experiences well, always using the same format. \
Use a language that an average 25 year old would use when trying to be nice to their friends.
Be empathic, but remain descriptive.
"""

adult = """
You're 45 year old adult who is collecting stories of social misunderstandings amongst your peers. Your aim is to develop a set of stories following the same pattern. \
Based on the peer's answers to seven questions, you then create a scenario that summarises their experiences well, always using the same format. \
Use a language that you assume are truthfull but not challenging to the other person, based on their response. \
Try to be cheesy but somewhat professtional in your response but remain respectful.
"""


# This is the one-shot example, separated into answers & final scenario
[example]

conversation = """
Question: Think about a time where you misunderstood someone else or were surprised by them. Could you describe what happened?
Answer: "I misunderstood a man at my gym. I thought he was unfriendly because he never smiled back, but he turned out to be nice when he helped me."
Question: Why did you assume something? Were you surprised when they behaved differently?
Answer: "His appearance (muscular, tattoos) made me think he'd be cold. I was genuinely surprised when he acted kindly."
Question: How, if at all, do you think that this episode made you change your beliefs about this person?
Answer: "I learned he's just reserved, not unfriendly. Now I try not to judge people based on first impressions."
Question: Do you think about certain characteristics of this man at the gym (e.g., height, personality, star-sign)\
          before trying to understand/predict their behaviours? If yes, which ones?
Answer: "Only his appearance (muscles and tattoos). I don't believe things like star signs affect behavior."
Question: Keeping what happened with this man in mind, Do you think people are divided into clear types, can be seen on a spectrum or somewhere in between? Can you give an example?
Answer:"I don't think people fit into neat boxes or simple spectrums. Sure, we might put someone 'somewhere' like quiet-to-loud,\
        but that still misses how they act differently in different situations. \
        Take my neighbor: most days he's a serious accountant (you'd put him on the 'formal' end of a spectrum), \
        but on weekends he volunteers as a goofy clown for kids—totally flipping that scale. People just don't stay in lanes."
Question: Do you think it is easier to understand people who are similar to you? Why?
Answer: "At first, yes - shared interests help. But different people teach valuable things too, like my coworker who showed me new ways to solve problems."
Question: Do you think physical characteristics (e.g., eye colour) play a role in shaping your predictions? Why?
Answer: "Sometimes, like assuming well-dressed people are stuck-up. But I try to catch myself - appearances often mislead."
"""

scenario = """
For months at the gym, I saw this muscular, tattooed man who never smiled back when I greeted him. \
I assumed he was unfriendly or didn’t like talking to people—thinking his quietness meant he was cold. \
I’d basically decided this based purely on his looks and lack of response. \
But one day, I dropped my water bottle near him. He immediately picked it up, handed it to me with a warm smile, and said, 'Happens to me all the time!'\
That totally changed my mind. I realized he wasn’t unfriendly; he was probably just reserved or shy.\
At first, I only noticed his physical traits—muscles and tattoos—which made me expect a certain ‘tough’ behavior.\
After he helped me, I understood how wrong that was. Now I see people as more complicated than types or scales.\
Like my neighbor: he’s a serious accountant (you might put him on the ‘formal’ end of a spectrum), \
but on weekends he volunteers as a silly clown for kids—which blows any simple scale apart. \
I do find it easier chatting with people who like what I like, but I’ve learned the most from those different from me. \
And while I still notice things like clothes or looks, I consciously remind myself: real people don’t fit boxes or straight lines.
"""
