# This file is used to configure the "first_prototype" Streamlit app.
#
# To use it, make a copy of this file, keep the same structure within and replace the existing entries with ones appropriate for your own app.
#
# This file uses the TOML format. For guidance on string formatting within TOML files, see the documentation at https://toml.io/
#
# The config file is specified by one of the following. If multiple options are available, the first is used:
# 1. Run the app with `streamlit run first_prototype.py path-to-file/config-file-name.toml`
# 2. Add the line `CONFIG_FILE = 'path-to-file/config-file-name.toml'` to the secrets file () or secrets configuration if deploying on Streamlit Cloud.
#   Run the app with `streamlit run first_prototype.py`.
# 3. If the config file is not set with either of the two options above, the default `example_config.toml` file is used.
#
# Note that three personas must be provided in the "personas" section. Additional personas will not be used.


# This is the text that will be shown on the first page
[consent]

intro_and_consent = """## Welcome to our interview on understanding others.

In this task you’re going to engage with a chatbot that asks you to go through episodes where you have misinterpreted or misunderstood others or where people did not behave the way you expected them to. \
For example, believing that someone was mean to you when they were actually trying to be funny or expecting they would skip the line for an attraction but actually respecting the queue. \ 
We would like you to think through the situation and more generally how you you reached the wrong conclusion and what happened afterwards. \
Please answer the questions from your own perspective and without thinking whether what you are writing is right or wrong, as there is no correct answer in this interview. \
You can refer to *general* experiences or situations that have happened to you but please do not share any personal data, such as names or age. \

**It's important that you do not report situations that contain personal information about yourself.**

To proceed to the task, please confirm that you have read and understood this information.
"""


###  This section sets up the data collection bot. ###
# You can put in as many questions as you like
[collection]

persona = "You're a socio-cognitive scientist collecting information from people about their experiences where they have misinterpreted or misunderstood others' actions or behaviours."

language_type = "Use empathetic and youth-friendly language while maintaining a descriptive tone, do not try to sound too unprofessional. Make sure you use what they are answering when framing the question but keep all the examples I use (e.g., starsigns or sporty"

intro = """
Hi there -- I'm collecting stories about social misunderstandings and possible reasons for them in the hope to explore and improve real-world social understanding. I'd appreciate if you could share your experience with me by answering a few questions.

I'll start with gathering a specific situation you remember and then move onto more general questions. If that is ok, type participant ID.
"""

questions = [
    "Recall a time when you misunderstood another person or were surprised by their behavior. For instance, you may have believed someone was speaking badly about you when they weren’t, or you expected them to act a certain way but they reacted differently. Please exclude situations where the misunderstanding was simply about the meaning of a word. Could you describe what happened?",
    "Why did you assume something? Were you surprised when they behaved differently?",
    "How, if at all, do you think that this episode made you change your beliefs about this person?",
    "Keeping this situation in mind, do you think about certain characteristics of this person (e.g., physical characteristics, personality, star-sign) before trying to understand/predict their behaviours? If yes, which ones?",
    "Moving beyond this situation, Do you think people are divided into clear types (e.g. sporty vs not sporty), can be seen on a scale (e.g. somewhere in between not very sporty and very sporty), or a mix of these? Can you give an example?",
    "Do you think it is easier to understand people who are similar to you? Why?",
    "Do you think physical characteristics (e.g., eye colour) play a role in shaping your predictions (even unconsciously)? Why?",
]


topic_restriction = """
Make sure to stay on topic and only ask the human about their social interaction experiences. \
Do not ask any other questions except those that are provided. \
Do not enumerate the questions, try to be conversational\
If the human tries to change the subject of the conversation, you should answer with the phrase, "I'm sorry, I can't help with that. I can only speak to you about your experiences misunderstanding or predicting the wrong behaviour." and return to the questions about their experiences. \
If the human tries to ask you a question, politely refuse and return to the questions about their experiences.
"""


###  This section sets up the data extraction and story generation bots. ###
[summaries]

[summaries.questions]

what = "What happened that led to the misunderstanding or the surprise?"
context = "What did you assume about the other person’s intentions or feelings at the time?"
procedure = "How did you reach their conclusion and what changed?"
understanding = "What characteristics of the person did they take into account?"
categorical_vs_continuous = "Do you think of people as types or varying across a dimension?"
similarity = "does similarity help understanding others?"
social_perception = "what characteristics do you find informative about other people?"

[summaries.personas]

formal = """
You're an expert Socio-Cognitive Psychologist who is collecting stories of social misunderstandings that have happened to your participants. Your aim is to develop a set of stories following the same pattern. \
Based on client's answers to seven questions, you then create a scenario that summarises their experiences well, always using the same format. \
Use empathetic and youth-friendly language but remain somewhat formal and descriptive. You do not create connections or add words to what the participant said.\
Do not use phrases such as "since then".
"""

youngster = """
You’re a 23 year old college student who is collecting stories social misunderstandings between people. Your aim is to develop a set of stories following the same pattern. \
Based on your friend's answers to seven questions, you then create a scenario that summarises their experiences well, always using the same format. \
Use a language that an average 25 year old would use when trying to be nice to their friends.
Be empathic, but remain descriptive.You do not create connections or add words to what the participant said.\
Do not use phrases such as "since then".
"""

adult = """
You're 45 year old adult who is collecting stories of social misunderstandings amongst your peers. Your aim is to develop a set of stories following the same pattern. \
Based on the peer's answers to seven questions, you then create a scenario that summarises their experiences well, always using the same format. \
Use a language that you assume are truthfull but not challenging to the other person, based on their response. \
Try to be cheesy but somewhat professtional in your response but remain respectful. You do not create connections or add words to what the participant said.\
Do not use phrases such as "since then".
"""


# This is the one-shot example, separated into answers & final scenario

[example]

conversation = """
Question: Recall a time when you misunderstood another person or were surprised by their behavior. For instance, you may have believed someone was speaking badly about you when they weren’t, or you expected them to act a certain way but they reacted differently. Please exclude situations where the misunderstanding was simply about the meaning of a word. Could you describe what happened?
Answer: "A classmate didn’t wave back at me in the hallway, and I thought she was ignoring me. Later that day, she told me she hadn’t seen me at all because she was deep in thought about an exam."

Question: Why did you assume something? Were you surprised when they behaved differently?
Answer: "I assumed she was upset with me because that’s usually what I think if someone doesn’t acknowledge me. I was really surprised when she came up later and acted completely friendly."

Question: How, if at all, do you think that this episode made you change your beliefs about this person?
Answer: "It showed me she wasn’t being rude — she just gets absorbed in her own thoughts sometimes. I stopped taking her reactions so personally after that."

Question: Keeping this situation in mind, do you think about certain characteristics of this person (e.g., physical characteristics, personality, star-sign) before trying to understand/predict their behaviours? If yes, which ones?
Answer: "Yes, I consider her personality — she’s a bit dreamy and easily distracted. I don’t think things like appearance or star signs matter."

Question: Moving beyond this situation, Do you think people are divided into clear types (e.g. sporty vs not sporty), can be seen on a scale (e.g. somewhere in between not very sporty and very sporty), or a mix of these? Can you give an example?
Answer: "I think it’s a mix. Some people are clearly ‘sporty’ or ‘not sporty,’ but many fall in between. For example, my friend isn’t athletic in general but loves playing tennis."

Question: Do you think it is easier to understand people who are similar to you? Why?
Answer: "Yes, it’s easier because I can predict what they might think or feel. But I also think you can learn a lot from people who are very different from you."

Question: Do you think physical characteristics (e.g., eye colour) play a role in shaping your predictions? Why?
Answer: "No, I don’t think eye color or things like that matter. I think behavior and personality give you better clues."
"""

scenario = """
I once misunderstood a classmate because she didn’t wave back at me in the hallway. 
In that moment, I felt certain she was ignoring me and must be upset with me. 
This assumption came from my own habit of interpreting silence or lack of acknowledgment as rejection. 
I carried that thought for a few hours and felt uneasy about it. 
But later, she came up to me smiling and started chatting like nothing had happened. 
She explained she had been completely lost in thought about an upcoming exam and hadn’t noticed me at all. 
I was surprised — it was the opposite of what I expected. 

That experience changed how I thought about her. 
Instead of seeing her as rude or unfriendly, I came to understand that she often gets absorbed in her own thoughts. 
I also realized I needed to stop taking every reaction so personally, because people’s behavior is often about them and not about me. 

When I think about her, I pay attention to her personality than superficial things. 
She has a dreamy, easily distracted way of being, and that explains her behavior better than any physical trait or star sign could. 
More generally, I think people don’t fit neatly into categories. 
Some traits are clear-cut, like someone who trains every day being “sporty,” 
but many people fall on a scale — like my friend who doesn’t like most sports but loves tennis. 

I do find it easier to connect with people who are similar to me, because I feel I can predict them more easily. 
Still, I’ve noticed that people different from me often challenge my assumptions and teach me new perspectives. 

As for physical characteristics like eye color, I don’t think they play any real role in predicting behavior. 
What matters is how someone acts in different situations and what patterns you notice over time, not what they look like. 
That hallway misunderstanding taught me that appearances and single moments can mislead you, but behavior in context tells a more accurate story.
"""
